packages:
  - apps/*
  - packages/*

onlyBuiltDependencies:
  - '@newrelic/fn-inspect'
  - '@newrelic/native-metrics'
  - '@prisma/client'
  - '@prisma/engines'
  - '@tailwindcss/oxide'
  - esbuild
  - prisma
  - protobufjs
  - sharp
